using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.Tilemaps;
using Mapmate.UnityImporter.Runtime;

namespace Mapmate.UnityImporter.Editor
{
    public readonly struct MapmateAutoSetupResult
    {
        public readonly MapmateTilePalette tilePalette;
        public readonly MapmatePrefabPalette prefabPalette;
        public readonly MapmateImportSettings settings;

        public MapmateAutoSetupResult(MapmateTilePalette tilePalette, MapmatePrefabPalette prefabPalette, MapmateImportSettings settings)
        {
            this.tilePalette = tilePalette;
            this.prefabPalette = prefabPalette;
            this.settings = settings;
        }
    }

    public static class MapmateAutoSetup
    {
        private const string RootFolder = "Assets/Mapmate/AutoGenerated";
        private const string SpritesFolder = RootFolder + "/Sprites";
        private const string TilesFolder = RootFolder + "/Tiles";
        private const string PrefabsFolder = RootFolder + "/Prefabs";

        private const string TilePalettePath = RootFolder + "/MapmateTilePalette.asset";
        private const string PrefabPalettePath = RootFolder + "/MapmatePrefabPalette.asset";
        private const string SettingsPath = RootFolder + "/MapmateImportSettings.asset";

        [MenuItem("Tools/Mapmate/Setup Defaults")]
        public static void SetupMenu()
        {
            var r = EnsureDefaults();
            EditorGUIUtility.PingObject(r.settings);
        }

        public static MapmateAutoSetupResult EnsureDefaults()
        {
            EnsureFolder("Assets/Mapmate");
            EnsureFolder(RootFolder);
            EnsureFolder(SpritesFolder);
            EnsureFolder(TilesFolder);
            EnsureFolder(PrefabsFolder);

            var settings = LoadOrCreateAsset<MapmateImportSettings>(SettingsPath);
            ApplyRecommendedDefaults(settings);

            var tilePalette = LoadOrCreateAsset<MapmateTilePalette>(TilePalettePath);
            var prefabPalette = LoadOrCreateAsset<MapmatePrefabPalette>(PrefabPalettePath);

            EnsureDefaultTiles(tilePalette);
            EnsureDefaultPrefabs(prefabPalette);

            EditorUtility.SetDirty(settings);
            EditorUtility.SetDirty(tilePalette);
            EditorUtility.SetDirty(prefabPalette);
            AssetDatabase.SaveAssets();

            return new MapmateAutoSetupResult(tilePalette, prefabPalette, settings);
        }

        private static void ApplyRecommendedDefaults(MapmateImportSettings settings)
        {
            if (settings == null) return;
            settings.reimportMode = MapmateReimportMode.PreserveUserEdits;
            settings.clearExistingChildren = false;
            settings.tilemapLayout = MapmateTilemapLayout.PerRoom;
            settings.useLayeredTilemaps = true;
            settings.addDoorEndpointAutoTransition2D = true;
            settings.ensureDefaultTransitionHandler = true;
            settings.ensureCameraFollow = false;
            settings.configureExistingMainCamera = false;
            settings.addTilemapCollider2D = true;
            settings.addCompositeCollider2D = true;
            settings.logImportSummary = true;
        }

        private static void EnsureDefaultTiles(MapmateTilePalette tilePalette)
        {
            // tileId는 프론트 exporter의 기본 매핑을 기준으로 함:
            // 1 solid, 2 platform, 3 spike, 4 acid, 5 breakable, 6 door
            var solidSprite = EnsureSpriteAsset(SpritesFolder + "/solid.png", new Color32(60, 60, 60, 255));
            var platformSprite = EnsureSpriteAsset(SpritesFolder + "/platform.png", new Color32(139, 69, 19, 255));
            var spikeSprite = EnsureSpriteAsset(SpritesFolder + "/spike.png", new Color32(255, 80, 80, 255));
            var acidSprite = EnsureSpriteAsset(SpritesFolder + "/acid.png", new Color32(0, 220, 120, 255));
            var breakableSprite = EnsureSpriteAsset(SpritesFolder + "/breakable.png", new Color32(150, 120, 90, 255));
            var doorSprite = EnsureSpriteAsset(SpritesFolder + "/door.png", new Color32(74, 144, 217, 255));

            var solidTile = EnsureTileAsset(TilesFolder + "/SolidTile.asset", solidSprite, Tile.ColliderType.Grid);
            var platformTile = EnsureTileAsset(TilesFolder + "/PlatformTile.asset", platformSprite, Tile.ColliderType.Grid);
            var spikeTile = EnsureTileAsset(TilesFolder + "/SpikeTile.asset", spikeSprite, Tile.ColliderType.Grid);
            var acidTile = EnsureTileAsset(TilesFolder + "/AcidTile.asset", acidSprite, Tile.ColliderType.Grid);
            var breakableTile = EnsureTileAsset(TilesFolder + "/BreakableTile.asset", breakableSprite, Tile.ColliderType.Grid);
            var doorTile = EnsureTileAsset(TilesFolder + "/DoorTile.asset", doorSprite, Tile.ColliderType.Grid);

            EnsureTilePaletteEntries(tilePalette,
                (1, "solid", solidTile),
                (2, "platform", platformTile),
                (3, "spike", spikeTile),
                (4, "acid", acidTile),
                (5, "breakable", breakableTile),
                (6, "door", doorTile));
        }

        private static void EnsureDefaultPrefabs(MapmatePrefabPalette prefabPalette)
        {
            var playerSprite = EnsureSpriteAsset(SpritesFolder + "/player.png", new Color32(255, 230, 120, 255));
            var doorSprite = EnsureSpriteAsset(SpritesFolder + "/door_obj.png", new Color32(74, 144, 217, 255));
            var spawnSprite = EnsureSpriteAsset(SpritesFolder + "/spawn.png", new Color32(100, 200, 255, 255));

            var playerPrefab = EnsurePlayerPrefab(PrefabsFolder + "/Player.prefab", playerSprite);
            var doorPrefab = EnsureSimpleSpritePrefab(PrefabsFolder + "/Door.prefab", "Door", doorSprite);
            var portalPrefab = EnsureSimpleSpritePrefab(PrefabsFolder + "/Portal.prefab", "Portal", doorSprite);
            var spawnPrefab = EnsureSpawnPointPrefab(PrefabsFolder + "/SpawnPoint.prefab", spawnSprite);

            EnsurePrefabPaletteEntries(prefabPalette,
                ("Player", playerPrefab),
                ("Door", doorPrefab),
                ("Portal", portalPrefab),
                ("spawn_point", spawnPrefab),
                ("transition", doorPrefab),
                ("npc", EnsureSimpleSpritePrefab(PrefabsFolder + "/Npc.prefab", "Npc", EnsureSpriteAsset(SpritesFolder + "/npc.png", new Color32(200, 170, 255, 255)))));
        }

        private static Sprite EnsureSpriteAsset(string assetPath, Color32 color)
        {
            if (!assetPath.StartsWith("Assets/", StringComparison.Ordinal))
                throw new ArgumentException("assetPath must be under Assets/");

            var projectRoot = Directory.GetParent(Application.dataPath)?.FullName;
            if (string.IsNullOrEmpty(projectRoot)) throw new Exception("Failed to resolve Unity project root");
            var abs = Path.Combine(projectRoot, assetPath);
            if (!File.Exists(abs))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(abs) ?? projectRoot);
                var tex = new Texture2D(16, 16, TextureFormat.RGBA32, false);
                var pixels = new Color32[16 * 16];
                for (var i = 0; i < pixels.Length; i++) pixels[i] = color;
                tex.SetPixels32(pixels);
                tex.Apply();

                var png = tex.EncodeToPNG();
                UnityEngine.Object.DestroyImmediate(tex);
                File.WriteAllBytes(abs, png);
                AssetDatabase.ImportAsset(assetPath);
            }

            var importer = (TextureImporter)AssetImporter.GetAtPath(assetPath);
            if (importer != null)
            {
                var changed = false;
                if (importer.textureType != TextureImporterType.Sprite) { importer.textureType = TextureImporterType.Sprite; changed = true; }
                if (importer.spritePixelsPerUnit != 16f) { importer.spritePixelsPerUnit = 16f; changed = true; }
                if (importer.filterMode != FilterMode.Point) { importer.filterMode = FilterMode.Point; changed = true; }
                if (importer.mipmapEnabled) { importer.mipmapEnabled = false; changed = true; }
                if (changed) importer.SaveAndReimport();
            }

            return AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
        }

        private static Tile EnsureTileAsset(string assetPath, Sprite sprite, Tile.ColliderType colliderType)
        {
            var tile = AssetDatabase.LoadAssetAtPath<Tile>(assetPath);
            if (tile == null)
            {
                tile = ScriptableObject.CreateInstance<Tile>();
                AssetDatabase.CreateAsset(tile, assetPath);
            }

            tile.sprite = sprite;
            tile.colliderType = colliderType;
            EditorUtility.SetDirty(tile);
            return tile;
        }

        private static GameObject EnsurePlayerPrefab(string assetPath, Sprite sprite)
        {
            var existing = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (existing != null) return existing;

            var go = new GameObject("Player");
            go.tag = "Player";

            var sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = sprite;

            var rb = go.AddComponent<Rigidbody2D>();
            rb.gravityScale = 3f;
            rb.freezeRotation = true;

            var col = go.AddComponent<BoxCollider2D>();
            col.size = new Vector2(0.8f, 0.9f);

            go.AddComponent<MapmatePlayerController2D>();

            var prefab = PrefabUtility.SaveAsPrefabAsset(go, assetPath);
            UnityEngine.Object.DestroyImmediate(go);
            return prefab;
        }

        private static GameObject EnsureSpawnPointPrefab(string assetPath, Sprite sprite)
        {
            var existing = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (existing != null) return existing;

            var go = new GameObject("spawn_point");
            var sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = sprite;
            go.AddComponent<MapmateSpawnPoint>();

            var prefab = PrefabUtility.SaveAsPrefabAsset(go, assetPath);
            UnityEngine.Object.DestroyImmediate(go);
            return prefab;
        }

        private static GameObject EnsureSimpleSpritePrefab(string assetPath, string name, Sprite sprite)
        {
            var existing = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (existing != null) return existing;

            var go = new GameObject(name);
            var sr = go.AddComponent<SpriteRenderer>();
            sr.sprite = sprite;

            var prefab = PrefabUtility.SaveAsPrefabAsset(go, assetPath);
            UnityEngine.Object.DestroyImmediate(go);
            return prefab;
        }

        private static void EnsureTilePaletteEntries(MapmateTilePalette tilePalette, params (int tileId, string tileKey, TileBase tile)[] entries)
        {
            if (tilePalette == null) return;
            var so = new SerializedObject(tilePalette);
            var prop = so.FindProperty("entries");
            var existing = new System.Collections.Generic.HashSet<int>();
            for (var i = 0; i < prop.arraySize; i++)
            {
                var e = prop.GetArrayElementAtIndex(i);
                existing.Add(e.FindPropertyRelative("tileId").intValue);
            }

            for (var i = 0; i < entries.Length; i++)
            {
                if (existing.Contains(entries[i].tileId)) continue;
                var idx = prop.arraySize;
                prop.InsertArrayElementAtIndex(idx);
                var e = prop.GetArrayElementAtIndex(idx);
                e.FindPropertyRelative("tileId").intValue = entries[i].tileId;
                e.FindPropertyRelative("tileKey").stringValue = entries[i].tileKey;
                e.FindPropertyRelative("tile").objectReferenceValue = entries[i].tile;
            }

            so.ApplyModifiedPropertiesWithoutUndo();
        }

        private static void EnsurePrefabPaletteEntries(MapmatePrefabPalette palette, params (string prefabKey, GameObject prefab)[] entries)
        {
            if (palette == null) return;
            var so = new SerializedObject(palette);
            var prop = so.FindProperty("entries");
            var existing = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < prop.arraySize; i++)
            {
                var e = prop.GetArrayElementAtIndex(i);
                existing.Add(e.FindPropertyRelative("prefabKey").stringValue ?? string.Empty);
            }

            for (var i = 0; i < entries.Length; i++)
            {
                if (existing.Contains(entries[i].prefabKey ?? string.Empty)) continue;
                var idx = prop.arraySize;
                prop.InsertArrayElementAtIndex(idx);
                var e = prop.GetArrayElementAtIndex(idx);
                e.FindPropertyRelative("prefabKey").stringValue = entries[i].prefabKey;
                e.FindPropertyRelative("prefab").objectReferenceValue = entries[i].prefab;
            }

            so.ApplyModifiedPropertiesWithoutUndo();
        }

        private static T LoadOrCreateAsset<T>(string assetPath) where T : ScriptableObject
        {
            var existing = AssetDatabase.LoadAssetAtPath<T>(assetPath);
            if (existing != null) return existing;

            var inst = ScriptableObject.CreateInstance<T>();
            AssetDatabase.CreateAsset(inst, assetPath);
            return inst;
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            var parent = Path.GetDirectoryName(path)?.Replace("\\", "/");
            var name = Path.GetFileName(path);
            if (string.IsNullOrEmpty(parent) || string.IsNullOrEmpty(name)) return;
            if (!AssetDatabase.IsValidFolder(parent)) EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, name);
        }
    }
}

